import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/assets/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NB IoT",
  description: "Generated by BWSoft",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className="h-full" style={inter.style}>
        {children}
      </body>
    </html>
  );
}
