import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/assets/globals.css";
import { NavBar } from "../ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NB IoT",
  description: "Generated by BWSoft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        style={inter.style}
        className="h-full grid grid-rows-[min-content_1fr]"
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
